"""Manual collocations for top-500 vocabulary PDF generation."""

from __future__ import annotations

import json
import re
from pathlib import Path

ASSETS = Path(__file__).resolve().parent / "assets"
TOP500_PATH = ASSETS / "_top500_words.json"

EMPTY_PRONOUNS = frozenset({"him", "their", "them", "its"})


def normalize_key(word: str) -> str:
    w = word.strip().lower()
    w = re.sub(r"\s*\([^)]*\)", "", w)
    w = re.sub(r"\s*=.*$", "", w)
    w = re.sub(r"\s+modal\s*$", "", w, flags=re.I)
    return w.strip().rstrip(".")


def load_top500_base_words(path: Path = TOP500_PATH) -> list[str]:
    """Return sorted unique normalized base words from _top500_words.json."""
    raw = json.loads(path.read_text(encoding="utf-8"))
    seen: set[str] = set()
    words: list[str] = []
    for item in raw:
        key = normalize_key(item["word"])
        if key not in seen:
            seen.add(key)
            words.append(key)
    return sorted(words)


COLLOCATIONS: dict[str, list[tuple[str, str]]] = {
    "able": [('be able to', '能够'), ('able to swim', '会游泳'), ('physically able', '身体健全')],
    "across": [('across the street', '街对面'), ('come across', '偶然遇到'), ('run across', '跑过')],
    "action": [('take action', '采取行动'), ('action movie', '动作片'), ('in action', '在行动中')],
    "activity": [('outdoor activity', '户外活动'), ('class activity', '课堂活动'), ('physical activity', '体育活动')],
    "add": [('add up', '加起来'), ('add to', '增加'), ('add sugar', '加糖')],
    "administration": [('school administration', '学校管理层'), ('public administration', '公共管理'), ('business administration', '工商管理')],
    "after": [('after school', '放学后'), ('after all', '毕竟'), ('day after day', '日复一日')],
    "against": [('against the wall', '靠墙'), ('fight against', '对抗'), ('go against', '违背')],
    "age": [('at the age of', '在…岁'), ('old age', '老年'), ('age group', '年龄组')],
    "agency": [('travel agency', '旅行社'), ('news agency', '通讯社'), ('government agency', '政府机构')],
    "ago": [('long ago', '很久以前'), ('a while ago', '刚才'), ('years ago', '几年前')],
    "agree": [('agree with sb', '同意某人'), ('agree to do', '答应做'), ('agree on sth', '就…达成一致')],
    "air": [('fresh air', '新鲜空气'), ('on the air', '广播中'), ('by air', '乘飞机')],
    "all": [('all day', '整天'), ('all over', '到处'), ('after all', '毕竟')],
    "allow": [('allow sb to do', '允许某人做'), ('not allowed', '不允许'), ('allow for', '考虑到')],
    "almost": [('almost every', '几乎每'), ('almost done', '快完成了'), ('almost never', '几乎从不')],
    "already": [('already know', '已经知道'), ('have already', '已经'), ('already left', '已经离开')],
    "although": [('although tired', '虽然累'), ('although small', '虽然小'), ('although it rained', '虽然下雨了')],
    "always": [('always remember', '永远记得'), ('as always', '像往常一样'), ('almost always', '几乎总是')],
    "american": [('American English', '美式英语'), ('American culture', '美国文化'), ('American dream', '美国梦')],
    "among": [('among friends', '朋友之间'), ('among others', '其中'), ('among the best', '最好的之一')],
    "another": [('another day', '改天'), ('one another', '彼此'), ('another time', '另一次')],
    "any": [('any time', '任何时候'), ('any more', '再'), ('if any', '如果有的话')],
    "anyone": [('anyone else', '其他人'), ('hardly anyone', '几乎没有人'), ('ask anyone', '问任何人')],
    "anything": [('anything else', '别的什么'), ('if anything', '如果有的话'), ('anything wrong', '出问题了')],
    "appear": [('appear to be', '似乎是'), ('suddenly appear', '突然出现'), ('appear on TV', '上电视')],
    "area": [('local area', '本地区'), ('rural area', '农村地区'), ('in the area', '在这一带')],
    "arm": [('right arm', '右臂'), ('arm in arm', '手挽手'), ('break an arm', '摔断手臂')],
    "around": [('look around', '环顾'), ('all around', '周围'), ('come around', '过来')],
    "art": [('art class', '美术课'), ('modern art', '现代艺术'), ('work of art', '艺术品')],
    "as": [('as well', '也'), ('as soon as', '一…就'), ('such as', '例如')],
    "ask": [('ask for', '请求'), ('ask a question', '提问'), ('ask sb to do', '请某人做')],
    "attention": [('pay attention', '注意'), ('draw attention', '引起注意'), ('attract attention', '吸引注意')],
    "author": [('famous author', '著名作家'), ('book author', '书籍作者'), ('best-selling author', '畅销作家')],
    "available": [('readily available', '随时可得'), ('not available', '暂无'), ('make available', '提供')],
    "away": [('right away', '立刻'), ('far away', '很远'), ('throw away', '扔掉')],
    "baby": [('baby boy', '男婴'), ('have a baby', '生孩子'), ('baby food', '婴儿食品')],
    "back": [('come back', '回来'), ('look back', '回顾'), ('pay back', '偿还')],
    "bank": [('bank account', '银行账户'), ('river bank', '河岸'), ('blood bank', '血库')],
    "base": [('military base', '军事基地'), ('base on', '基于'), ('first base', '一垒')],
    "be": [('be able to', '能够'), ('be interested in', '对…感兴趣'), ('be good at', '擅长')],
    "because": [('because of', '因为'), ('just because', '就因为')],
    "become": [('become a teacher', '成为老师'), ('become famous', '成名'), ('become clear', '变得清楚')],
    "bed": [('go to bed', '上床睡觉'), ('make the bed', '铺床'), ('in bed', '在床上')],
    "before": [('before long', '不久'), ('long before', '很久以前'), ('before class', '课前')],
    "begin": [('begin with', '以…开始'), ('begin to do', '开始做'), ('begin again', '重新开始')],
    "behind": [('behind the door', '门后'), ('fall behind', '落后'), ('leave behind', '留下')],
    "believe": [('believe in', '相信'), ('believe it or not', '信不信由你'), ('hard to believe', '难以置信')],
    "between": [('between you and me', '你我之间'), ('in between', '在中间'), ('between classes', '课间')],
    "billion": [('two billion people', '二十亿人'), ('billions of stars', '数十亿颗星星')],
    "blood": [('blood type', '血型'), ('blood pressure', '血压'), ('lose blood', '失血')],
    "board": [('on board', '在船上/机上'), ('school board', '校董会'), ('cutting board', '砧板')],
    "body": [('human body', '人体'), ('body language', '肢体语言'), ('whole body', '全身')],
    "book": [('book a ticket', '订票'), ('read a book', '读书'), ('by the book', '按规矩')],
    "both": [('both ... and', '既…又'), ('both sides', '双方'), ('both of us', '我们俩')],
    "break": [('break down', '出故障'), ('break up', '分手'), ('take a break', '休息一下')],
    "build": [('build up', '建立'), ('build a house', '盖房子'), ('build on', '在…基础上发展')],
    "building": [('office building', '办公楼'), ('tall building', '高楼'), ('building materials', '建材')],
    "business": [('do business', '做生意'), ('business trip', '出差'), ('small business', '小企业')],
    "buy": [('buy a gift', '买礼物'), ('buy time', '争取时间'), ('buy into', '相信')],
    "call": [('call back', '回电话'), ('phone call', '电话'), ('call for', '要求')],
    "campaign": [('election campaign', '竞选活动'), ('advertising campaign', '广告活动'), ('campaign for', '为…而奔走')],
    "can": [('I can swim', '我会游泳'), ('can you help?', '你能帮忙吗？'), ('as fast as you can', '尽你所能快')],
    "car": [('by car', '开车'), ('car park', '停车场'), ('police car', '警车')],
    "care": [('take care', '小心'), ('take care of', '照顾'), ('health care', '医疗保健')],
    "carry": [('carry on', '继续'), ('carry out', '执行'), ('carry a bag', '提包')],
    "case": [('in case', '以防'), ('in that case', '那样的话'), ('phone case', '手机壳')],
    "catch": [('catch a cold', '感冒'), ('catch up', '赶上'), ('catch the bus', '赶公交')],
    "cause": [('cause trouble', '惹麻烦'), ('cause and effect', '因果'), ('good cause', '正当理由')],
    "centre": [('city centre', '市中心'), ('shopping centre', '购物中心'), ('at the centre', '在中心')],
    "century": [('21st century', '21世纪'), ('turn of the century', '世纪之交')],
    "certain": [('for certain', '肯定'), ('a certain', '某个'), ('make certain', '确保')],
    "chance": [('by chance', '偶然'), ('take a chance', '冒险一试'), ('stand a chance', '有机会')],
    "change": [("change one's mind", '改变主意'), ('climate change', '气候变化'), ('small change', '零钱')],
    "choice": [('make a choice', '做出选择'), ('no choice', '别无选择'), ('good choice', '好选择')],
    "choose": [('choose from', '从中选择'), ('choose to do', '选择做'), ('choose wisely', '明智选择')],
    "church": [('go to church', '去教堂'), ('church service', '礼拜'), ('near the church', '教堂附近')],
    "city": [('city life', '城市生活'), ('across the city', '全城'), ('big city', '大城市')],
    "class": [('in class', '在课堂上'), ('first class', '头等'), ('class meeting', '班会')],
    "clear": [('make it clear', '说清楚'), ('clear up', '放晴/澄清'), ('clear answer', '明确答复')],
    "close": [('close to', '靠近'), ('close the door', '关门'), ('close friend', '密友')],
    "college": [('go to college', '上大学'), ('college student', '大学生'), ('college entrance exam', '高考')],
    "common": [('in common', '共同'), ('common sense', '常识'), ('common problem', '常见问题')],
    "company": [('keep company', '陪伴'), ('insurance company', '保险公司'), ('in company with', '与…一起')],
    "computer": [('computer science', '计算机科学'), ('personal computer', '个人电脑'), ('computer room', '机房')],
    "concern": [('concern about', '对…担忧'), ('of concern', '令人担忧'), ('main concern', '主要关切')],
    "condition": [('in good condition', '状况良好'), ('on condition that', '条件是'), ('weather condition', '天气状况')],
    "consider": [('consider doing', '考虑做'), ('all things considered', '总的来说')],
    "continue": [('continue to do', '继续做'), ('continue with', '继续'), ('to be continued', '未完待续')],
    "control": [('under control', '在控制下'), ('out of control', '失控'), ('remote control', '遥控器')],
    "cost": [('at the cost of', '以…为代价'), ('cost of living', '生活成本'), ('low cost', '低成本')],
    "could": [('could you help?', '你能帮忙吗？'), ('could be true', '可能是真的'), ('could not sleep', '睡不着')],
    "country": [('home country', '祖国'), ('across the country', '全国'), ('country music', '乡村音乐')],
    "couple": [('a couple of', '几个'), ('married couple', '夫妻'), ('a couple days', '几天')],
    "course": [('of course', '当然'), ('main course', '主菜'), ('in the course of', '在…过程中')],
    "court": [('basketball court', '篮球场'), ('go to court', '上法庭'), ('tennis court', '网球场')],
    "cover": [('cover up', '掩盖'), ('book cover', '封面'), ('cover the cost', '承担费用')],
    "create": [('create jobs', '创造就业'), ('create a chance', '创造机会'), ('create problems', '制造麻烦')],
    "culture": [('local culture', '本地文化'), ('popular culture', '流行文化'), ('culture shock', '文化冲击')],
    "data": [('collect data', '收集数据'), ('personal data', '个人数据'), ('data analysis', '数据分析')],
    "daughter": [('elder daughter', '大女儿'), ('only daughter', '独生女'), ('young daughter', '年幼的女儿')],
    "deal": [('deal with', '处理'), ('a great deal', '大量'), ('big deal', '大事')],
    "death": [('cause of death', '死因'), ('life and death', '生死'), ('sudden death', '猝死')],
    "decide": [('decide to do', '决定做'), ('decide on', '选定'), ('hard to decide', '难以决定')],
    "decision": [('make a decision', '做决定'), ('final decision', '最终决定'), ('right decision', '正确决定')],
    "defence": [('in defence of', '为…辩护'), ('self-defence', '自卫'), ('national defence', '国防')],
    "describe": [('describe as', '描述为'), ('hard to describe', '难以描述'), ('describe in detail', '详细描述')],
    "develop": [('develop skills', '培养技能'), ('develop into', '发展成'), ('develop a habit', '养成习惯')],
    "development": [('economic development', '经济发展'), ('personal development', '个人发展'), ('sustainable development', '可持续发展')],
    "die": [('die of', '死于'), ('die down', '平息'), ('die for', '为…而死')],
    "difference": [('make a difference', '有影响'), ('tell the difference', '分辨'), ('big difference', '很大差别')],
    "difficult": [('difficult to do', '难以做'), ('very difficult', '非常困难'), ('difficult situation', '困境')],
    "director": [('film director', '电影导演'), ('school director', '校长'), ('art director', '艺术总监')],
    "doctor": [('see a doctor', '看医生'), ('family doctor', '家庭医生'), ('Doctor Wang', '王医生')],
    "door": [('open the door', '开门'), ('next door', '隔壁'), ('front door', '前门')],
    "down": [('sit down', '坐下'), ('write down', '写下'), ('calm down', '冷静')],
    "draw": [('draw a picture', '画画'), ('draw attention', '引起注意'), ('draw a conclusion', '得出结论')],
    "drive": [('drive a car', '开车'), ('drive sb crazy', '把人逼疯'), ('drive away', '开走')],
    "drop": [('drop by', '顺便拜访'), ('drop out', '退学'), ('drop off', '放下')],
    "drug": [('drug store', '药店'), ('take drugs', '吸毒'), ('drug abuse', '药物滥用')],
    "during": [('during the day', '白天'), ('during the summer', '夏天期间'), ('during class', '上课时')],
    "each": [('each other', '互相'), ('each day', '每天'), ('each one', '每一个')],
    "early": [('early morning', '清晨'), ('get up early', '早起'), ('as early as', '早在')],
    "easy": [('easy to do', '容易做'), ('take it easy', '放轻松'), ('easy job', '轻松的工作')],
    "education": [('higher education', '高等教育'), ('physical education', '体育'), ('education system', '教育体系')],
    "effect": [('in effect', '实际上'), ('side effect', '副作用'), ('take effect', '生效')],
    "effort": [('make an effort', '努力'), ('joint effort', '共同努力'), ('spare no effort', '不遗余力')],
    "either": [('either ... or', '要么…要么'), ('either way', '不管怎样'), ('not either', '也不')],
    "else": [('or else', '否则'), ('something else', '别的东西'), ('anyone else', '其他人')],
    "end": [('in the end', '最终'), ('at the end of', '在…末尾'), ('come to an end', '结束')],
    "energy": [('save energy', '节约能源'), ('full of energy', '精力充沛'), ('renewable energy', '可再生能源')],
    "enough": [('good enough', '足够好'), ('enough for', '对…足够'), ('sure enough', '果然')],
    "enter": [('enter a room', '进入房间'), ('enter a competition', '参加比赛'), ('enter college', '上大学')],
    "especially": [('especially important', '尤其重要'), ('especially for you', '特别为你'), ('especially when tired', '尤其累的时候')],
    "even": [('even if', '即使'), ('even though', '虽然'), ('even better', '更好')],
    "event": [('main event', '主要活动'), ('sporting event', '体育赛事'), ('in the event of', '万一')],
    "ever": [('ever since', '自从'), ('hardly ever', '几乎从不'), ('for ever', '永远')],
    "every": [('every day', '每天'), ('every time', '每次'), ('every one', '每一个')],
    "everyone": [('everyone knows', '人人都知道'), ('almost everyone', '几乎每个人'), ('tell everyone', '告诉每个人')],
    "everything": [('everything is fine', '一切都好'), ('almost everything', '几乎一切'), ('everything else', '其他一切')],
    "evidence": [('clear evidence', '明确证据'), ('in evidence', '明显的'), ('gather evidence', '收集证据')],
    "expect": [('expect to do', '期望做'), ('as expected', '如预期'), ("didn't expect that", '没想到')],
    "experience": [('work experience', '工作经验'), ('gain experience', '积累经验'), ('learning experience', '学习经历')],
    "explain": [('explain to sb', '向某人解释'), ('explain why', '解释为什么'), ('hard to explain', '难以解释')],
    "fact": [('in fact', '事实上'), ('matter of fact', '事实'), ('face the fact', '面对事实')],
    "fall": [('fall asleep', '睡着'), ('fall in love', '坠入爱河'), ('fall behind', '落后')],
    "far": [('so far', '到目前为止'), ('far from', '远非'), ('as far as', '就…而言')],
    "federal": [('federal government', '联邦政府'), ('federal law', '联邦法律'), ('federal court', '联邦法院')],
    "feel": [('feel like', '想要'), ('feel free', '请随意'), ('feel sorry', '感到抱歉')],
    "few": [('a few', '几个'), ('very few', '很少'), ('few people', '少数人')],
    "field": [('in the field', '在实地'), ('field trip', '实地考察'), ('football field', '足球场')],
    "fight": [('fight for', '为…而战'), ('fight against', '对抗'), ('fight back', '反击')],
    "figure": [('figure out', '弄清楚'), ('public figure', '公众人物'), ('key figure', '关键人物')],
    "fill": [('fill in', '填写'), ('fill up', '装满'), ('fill with', '充满')],
    "fine": [('fine art', '美术'), ("that's fine", '没关系'), ('fine weather', '好天气')],
    "fire": [('on fire', '着火'), ('fire alarm', '火警'), ('open fire', '开火')],
    "floor": [('on the floor', '在地板上'), ('ground floor', '一楼'), ('dance floor', '舞池')],
    "focus": [('focus on', '专注于'), ('in focus', '对焦'), ('lose focus', '分心')],
    "follow": [('follow the rules', '遵守规则'), ('follow sb', '跟随某人'), ('as follows', '如下')],
    "foot": [('on foot', '步行'), ('at the foot of', '在…脚下'), ('set foot in', '踏入')],
    "force": [('by force', '用武力'), ('in force', '生效'), ('air force', '空军')],
    "foreign": [('foreign language', '外语'), ('foreign student', '留学生'), ('foreign country', '外国')],
    "form": [('fill in a form', '填表'), ('in the form of', '以…形式'), ('take form', '成形')],
    "former": [('former student', '以前的学生'), ('former president', '前总统'), ('former teacher', '以前的老师')],
    "friend": [('best friend', '最好的朋友'), ('make friends', '交朋友'), ('close friend', '密友')],
    "full": [('full of', '充满'), ('full time', '全职'), ('in full', '全部')],
    "future": [('in the future', '将来'), ('for the future', '为了未来'), ('bright future', '光明未来')],
    "game": [('video game', '电子游戏'), ('play a game', '玩游戏'), ('ball game', '球赛')],
    "give": [('give up', '放弃'), ('give back', '归还'), ('give a hand', '帮忙')],
    "go": [('go on', '继续'), ('go out', '出去'), ('let go', '放手')],
    "goal": [('set a goal', '设定目标'), ('score a goal', '进球'), ('long-term goal', '长期目标')],
    "good": [('good at', '擅长'), ('good luck', '好运'), ('for good', '永久')],
    "government": [('local government', '地方政府'), ('central government', '中央政府')],
    "ground": [('on the ground', '在地上'), ('common ground', '共同点'), ('ground floor', '一楼')],
    "group": [('group work', '小组合作'), ('age group', '年龄组'), ('in groups', '分组')],
    "grow": [('grow up', '长大'), ('grow into', '长成'), ('grow old', '变老')],
    "half": [('half an hour', '半小时'), ('in half', '分成两半'), ('half past', '半点')],
    "hand": [('by hand', '手工'), ('on the other hand', '另一方面'), ('hand in', '上交')],
    "happen": [('happen to do', '碰巧做'), ('what happened', '怎么了'), ('happen to sb', '发生在某人身上')],
    "hard": [('work hard', '努力工作'), ('hard to believe', '难以置信'), ('try hard', '努力尝试')],
    "health": [('good health', '健康'), ('mental health', '心理健康'), ('health care', '医疗保健')],
    "heart": [('heart disease', '心脏病'), ('by heart', '背诵'), ("break one's heart", '让人心碎')],
    "here": [('come here', '过来'), ('here and there', '各处'), ('here you are', '给你')],
    "high": [('high school', '高中'), ('high price', '高价'), ('fly high', '飞得高')],
    "him": [],
    "himself": [('by himself', '独自'), ('for himself', '为他自己'), ('proud of himself', '为自己骄傲')],
    "history": [('world history', '世界史'), ('make history', '创造历史'), ('in history', '在历史上')],
    "hit": [('hit the road', '上路'), ('hit sb', '打某人'), ('hit the target', '命中目标')],
    "hold": [('hold on', '等一下'), ('hold back', '抑制'), ('hold a meeting', '开会')],
    "home": [('at home', '在家'), ('go home', '回家'), ('home town', '家乡')],
    "hope": [('hope for', '希望'), ('in the hope of', '抱着…的希望'), ('hope so', '希望如此')],
    "hospital": [('in hospital', '住院'), ('go to hospital', '去医院'), ('hospital bed', '病床')],
    "hour": [('an hour ago', '一小时前'), ('half an hour', '半小时'), ('rush hour', '高峰时段')],
    "house": [('clean the house', '打扫房子'), ('house price', '房价'), ('full house', '满座')],
    "however": [('however hard', '无论多难'), ('however you like', '随你喜欢')],
    "human": [('human being', '人类'), ('human rights', '人权'), ('human nature', '人性')],
    "husband": [('husband and wife', '夫妻'), ('my husband', '我丈夫'), ('future husband', '未来的丈夫')],
    "idea": [('good idea', '好主意'), ('have no idea', '不知道'), ('main idea', '主旨')],
    "if": [('if possible', '如果可能'), ('if not', '如果不'), ('what if', '要是…怎么办')],
    "important": [('important to', '对…重要'), ('most important', '最重要'), ('important role', '重要作用')],
    "include": [('include in', '包含在'), ('not include', '不包括')],
    "increase": [('increase by', '增加了'), ('on the increase', '在增加'), ('price increase', '涨价')],
    "industry": [('heavy industry', '重工业'), ('film industry', '电影业'), ('service industry', '服务业')],
    "information": [('for your information', '供参考'), ('personal information', '个人信息'), ('more information', '更多信息')],
    "interest": [('take an interest in', '对…感兴趣'), ('places of interest', '名胜'), ('lose interest', '失去兴趣')],
    "international": [('international student', '留学生'), ('international trade', '国际贸易'), ('international news', '国际新闻')],
    "into": [('look into', '调查'), ('run into', '撞上'), ('translate into', '翻译成')],
    "its": [],
    "itself": [('by itself', '独自'), ('in itself', '本身'), ('the city itself', '城市本身')],
    "job": [('do a good job', '干得好'), ('job interview', '面试'), ('look for a job', '找工作')],
    "just": [('just now', '刚才'), ('just like', '就像'), ('just a minute', '稍等')],
    "keep": [('keep on', '继续'), ('keep up', '保持'), ('keep in mind', '记住')],
    "kid": [('when I was a kid', '我小时候'), ('school kid', '学童'), ('just a kid', '只是个孩子')],
    "kill": [('kill time', '消磨时间'), ('kill two birds', '一石二鸟')],
    "kind": [('kind of', '有点'), ('all kinds of', '各种'), ('kind to', '对…友好')],
    "know": [('know about', '了解'), ('you know', '你知道'), ('know for sure', '确定知道')],
    "land": [('land on', '降落在'), ('by land', '陆路'), ('land area', '陆地面积')],
    "large": [('large number', '大量'), ('at large', '逍遥法外'), ('large scale', '大规模')],
    "last": [('at last', '终于'), ('last night', '昨晚'), ('last but not least', '最后但同样重要')],
    "late": [('be late for', '迟到'), ('too late', '太晚了'), ('late at night', '深夜')],
    "law": [('break the law', '违法'), ('by law', '依法'), ('law school', '法学院')],
    "lead": [('lead to', '导致'), ('lead the way', '带路'), ('take the lead', '领先')],
    "leader": [('team leader', '队长'), ('political leader', '政治领袖'), ('great leader', '伟大领袖')],
    "learn": [('learn from', '向…学习'), ('learn by heart', '背诵'), ('learn about', '了解')],
    "least": [('at least', '至少'), ('not in the least', '一点也不'), ('least of all', '最不')],
    "leave": [('leave for', '动身去'), ('leave behind', '留下'), ('on leave', '休假')],
    "let": [('let go', '放手'), ('let sb do', '让某人做'), ('let alone', '更不用说')],
    "letter": [('write a letter', '写信'), ('capital letter', '大写字母'), ('letter of thanks', '感谢信')],
    "level": [('sea level', '海平面'), ('high level', '高水平'), ('on the level', '诚实的')],
    "life": [('daily life', '日常生活'), ('for life', '终身'), ('way of life', '生活方式')],
    "light": [('in the light of', '鉴于'), ('light up', '照亮'), ('traffic light', '红绿灯')],
    "likely": [('most likely', '很可能'), ('likely to', '可能'), ('not likely', '不太可能')],
    "line": [('in line', '排队'), ('on line', '在线'), ('line up', '排队')],
    "listen": [('listen to', '听'), ('listen carefully', '仔细听'), ('listen up', '听好了')],
    "little": [('a little', '一点'), ('little by little', '渐渐地'), ('too little', '太少')],
    "live": [('live on', '靠…生活'), ('live up to', '不辜负'), ('live a life', '过生活')],
    "local": [('local people', '当地人'), ('local news', '本地新闻'), ('local government', '地方政府')],
    "look": [('look for', '寻找'), ('look after', '照顾'), ('look forward to', '期待')],
    "lose": [('lose weight', '减肥'), ('lose face', '丢脸'), ("lose one's way", '迷路')],
    "lot": [('a lot of', '许多'), ('parking lot', '停车场'), ('thanks a lot', '多谢')],
    "low": [('low price', '低价'), ('low voice', '低声'), ('in low spirits', '情绪低落')],
    "major": [('major in', '主修'), ('major problem', '主要问题'), ('major role', '主要作用')],
    "make": [('make sure', '确保'), ('make up', '编造/化妆'), ('make a decision', '做决定')],
    "man": [('young man', '年轻人'), ('a man of honour', '一个正直的人'), ('no other man', '没有别人')],
    "many": [('too many', '太多'), ('how many', '多少'), ('many people', '许多人')],
    "market": [('stock market', '股市'), ('on the market', '上市'), ('market price', '市价')],
    "material": [('raw material', '原材料'), ('reading material', '阅读材料'), ('teaching material', '教材')],
    "matter": [('no matter', '不管'), ('as a matter of fact', '事实上'), ("what's the matter", '怎么了')],
    "may": [('May I come in?', '我可以进来吗？'), ('may be late', '可能迟到'), ('may I ask', '请问')],
    "maybe": [('maybe later', '也许稍后'), ('maybe so', '也许吧'), ('maybe not', '也许不')],
    "mean": [('mean to do', '打算做'), ('I mean', '我是说'), ('by all means', '一定')],
    "medical": [('medical care', '医疗'), ('medical student', '医学生'), ('medical history', '病史')],
    "member": [('family member', '家庭成员'), ('team member', '队员'), ('club member', '俱乐部成员')],
    "might": [('might be true', '可能是真的'), ('might help you', '可能帮到你'), ('might as well go', '不妨走')],
    "mind": [('keep in mind', '记住'), ("change one's mind", '改变主意'), ('never mind', '没关系')],
    "minute": [('wait a minute', '等一下'), ('last minute', '最后一刻'), ('in a minute', '马上')],
    "model": [('role model', '榜样'), ('model student', '模范学生'), ('fashion model', '模特')],
    "moment": [('at the moment', '此刻'), ('for a moment', '一会儿'), ('just a moment', '稍等')],
    "money": [('save money', '省钱'), ('make money', '赚钱'), ('pocket money', '零花钱')],
    "month": [('last month', '上个月'), ('next month', '下个月'), ('month by month', '逐月')],
    "more": [('more and more', '越来越多'), ('no more', '不再'), ('more than', '多于')],
    "move": [('move on', '继续'), ('move in', '搬入'), ('move forward', '前进')],
    "movement": [('slow movement', '慢动作'), ('independent movement', '独立运动')],
    "movie": [('action movie', '动作片'), ('go to the movies', '去看电影'), ('movie star', '电影明星')],
    "mr": [('Mr Smith', '史密斯先生'), ('Dear Mr Li', '尊敬的李先生')],
    "must": [('must finish today', '今天必须完成'), ('must be careful', '必须小心'), ('must not smoke', '禁止吸烟')],
    "myself": [('by myself', '独自'), ('myself included', '包括我自己'), ('talk to myself', '自言自语')],
    "nation": [('whole nation', '全国'), ('across the nation', '全国'), ('developing nation', '发展中国家')],
    "national": [('national team', '国家队'), ('national day', '国庆节'), ('national park', '国家公园')],
    "natural": [('natural resources', '自然资源'), ('natural beauty', '自然美'), ("it's natural", '这很自然')],
    "nature": [('human nature', '人性'), ('by nature', '天生'), ('in nature', '在自然界')],
    "near": [('near here', '这附近'), ('near the school', '学校附近'), ('come near', '靠近')],
    "nearly": [('nearly every', '几乎每'), ('nearly done', '快完成了'), ('nearly all', '几乎全部')],
    "need": [('in need of', '需要'), ('if need be', '如果需要'), ('meet the need', '满足需求')],
    "never": [('never mind', '没关系'), ('never forget', '永不忘记'), ('never again', '再也不')],
    "news": [('good news', '好消息'), ('bad news', '坏消息'), ('news report', '新闻报道')],
    "next": [('next to', '紧挨着'), ('next week', '下周'), ('next time', '下次')],
    "north": [('in the north', '在北方'), ('north of', '在…以北'), ('North America', '北美')],
    "not": [('not at all', '一点也不'), ('not yet', '还没有'), ('not only', '不仅')],
    "note": [('take note', '记下'), ('make a note', '做笔记'), ('note down', '记下')],
    "nothing": [('nothing but', '只不过'), ('nothing much', '没什么'), ('have nothing to do', '无事可做')],
    "number": [('a number of', '许多'), ('phone number', '电话号码'), ('large number', '大量')],
    "off": [('take off', '起飞/脱下'), ('turn off', '关掉'), ('pay off', '得到回报')],
    "offer": [('offer help', '提供帮助'), ('special offer', '特价'), ('on offer', '出售中')],
    "officer": [('police officer', '警察'), ('army officer', '军官'), ('security officer', '保安')],
    "official": [('government official', '政府官员'), ('official language', '官方语言'), ('official visit', '正式访问')],
    "often": [('quite often', '相当经常'), ('more often', '更经常'), ('often enough', '够经常')],
    "oh": [('oh no', '哦不'), ('oh well', '哦好吧'), ('oh dear', '天哪')],
    "oil": [('cooking oil', '食用油'), ('oil painting', '油画'), ('olive oil', '橄榄油')],
    "old": [('years old', '…岁'), ('grow old', '变老'), ('old friend', '老朋友')],
    "only": [('only child', '独生子女'), ('not only', '不仅'), ('only if', '只有当')],
    "open": [('open the door', '开门'), ('open up', '打开'), ('wide open', '大开着')],
    "or": [('tea or coffee', '茶还是咖啡'), ('now or never', '机不可失'), ('right or wrong', '对错')],
    "order": [('in order', '整齐'), ('in order to', '为了'), ('out of order', '出故障')],
    "organization": [('international organization', '国际组织'), ('non-profit organization', '非营利组织'), ('student organization', '学生组织')],
    "other": [('each other', '互相'), ('the other', '另一个'), ('other than', '除了')],
    "over": [('over there', '在那边'), ('all over', '到处'), ('over and over', '一遍又一遍')],
    "own": [("on one's own", '独自'), ("of one's own", '自己的'), ('own up', '承认')],
    "page": [('turn the page', '翻页'), ('front page', '头版'), ('next page', '下一页')],
    "paper": [('term paper', '学期论文'), ('on paper', '纸上'), ('paper work', '文书工作')],
    "parent": [('single parent', '单亲家长'), ('parent meeting', '家长会'), ('proud parent', '骄傲的家长')],
    "part": [('take part in', '参加'), ('part of', '…的一部分'), ('play a part', '起作用')],
    "party": [('birthday party', '生日派对'), ('dinner party', '晚宴'), ('political party', '政党')],
    "pass": [('pass by', '经过'), ('pass the exam', '通过考试'), ('pass on', '传递')],
    "patient": [('be patient with', '对…有耐心'), ('patient care', '病人护理'), ('stay patient', '保持耐心')],
    "pay": [('pay for', '付款'), ('pay attention', '注意'), ('pay back', '偿还')],
    "people": [('young people', '年轻人'), ('many people', '许多人'), ('people around', '周围的人')],
    "per": [('per day', '每天'), ('per person', '每人'), ('as per', '按照')],
    "performance": [('good performance', '表现好'), ('live performance', '现场演出'), ('school performance', '学业表现')],
    "perhaps": [('perhaps tomorrow', '也许明天'), ('perhaps not', '也许不'), ('perhaps so', '也许吧')],
    "period": [('long period', '长时期'), ('during the period', '在此期间'), ('free period', '空闲时段')],
    "person": [('in person', '亲自'), ('each person', '每个人'), ('nice person', '好人')],
    "personal": [('personal life', '私人生活'), ('personal opinion', '个人意见'), ('personal computer', '个人电脑')],
    "phone": [('phone call', '电话'), ('on the phone', '在通话'), ('phone number', '电话号码')],
    "pick": [('pick up', '捡起/接人'), ('pick out', '挑选'), ('pick a fight', '找茬')],
    "piece": [('a piece of', '一块/一片'), ('piece by piece', '一点一点'), ('piece together', '拼合')],
    "place": [('take place', '发生'), ('in the first place', '首先'), ('place an order', '下单')],
    "plan": [('make a plan', '制定计划'), ('plan to do', '计划做'), ('plan ahead', '提前规划')],
    "play": [('play a role', '起作用'), ('play sports', '做运动'), ('play with', '和…玩')],
    "point": [('point at', '指向'), ('point out', '指出'), ('at this point', '此时')],
    "police": [('police station', '警察局'), ('police officer', '警察'), ('call the police', '报警')],
    "policy": [('foreign policy', '外交政策'), ('make policy', '制定政策'), ('school policy', '校规')],
    "political": [('political party', '政党'), ('political leader', '政治领袖'), ('political view', '政治观点')],
    "poor": [('poor health', '健康不佳'), ('poor quality', '质量差'), ('feel poor', '感觉不舒服')],
    "population": [('population growth', '人口增长'), ('local population', '当地居民'), ('world population', '世界人口')],
    "position": [('in position', '就位'), ('take a position', '表态'), ('job position', '职位')],
    "possible": [('as ... as possible', '尽可能'), ('if possible', '如果可能'), ('make it possible', '使之可能')],
    "power": [('in power', '掌权'), ('power supply', '电源'), ('super power', '超级大国')],
    "practice": [('in practice', '实际上'), ('put into practice', '付诸实践'), ('target practice', '打靶')],
    "practise": [('practise English', '练英语'), ('practise every day', '每天练习'), ('practise the piano', '练钢琴')],
    "president": [('vice president', '副总统'), ('class president', '班长'), ('former president', '前总统')],
    "price": [('high price', '高价'), ('at a price', '以…价格'), ('price tag', '价签')],
    "private": [('in private', '私下'), ('private life', '私人生活'), ('private school', '私立学校')],
    "probably": [('probably true', '可能是真的'), ('most probably', '很可能'), ('will probably', '可能会')],
    "process": [('in the process of', '在…过程中'), ('learning process', '学习过程'), ('slow process', '缓慢的过程')],
    "produce": [('produce goods', '生产商品'), ('locally produced', '本地生产'), ('produce results', '产生结果')],
    "product": [('product quality', '产品质量'), ('dairy product', '乳制品'), ('new product', '新产品')],
    "programme": [('TV programme', '电视节目'), ('training programme', '培训项目'), ('study programme', '学习计划')],
    "project": [('school project', '学校项目'), ('work on a project', '做项目'), ('project manager', '项目经理')],
    "provide": [('provide for', '供养'), ('provide with', '提供'), ('provide help', '提供帮助')],
    "public": [('in public', '公开'), ('public transport', '公共交通'), ('general public', '公众')],
    "pull": [('pull out', '拔出'), ('pull together', '齐心协力'), ('pull up', '停车')],
    "push": [('push forward', '推进'), ('push the button', '按按钮'), ('push sb too far', '逼人太甚')],
    "put": [('put on', '穿上'), ('put off', '推迟'), ('put away', '收好')],
    "question": [('ask a question', '提问'), ('out of the question', '不可能'), ('without question', '毫无疑问')],
    "quite": [('quite good', '相当好'), ('quite sure', '很确定'), ('quite a lot', '很多')],
    "race": [('race against time', '与时间赛跑'), ('human race', '人类'), ('foot race', '赛跑')],
    "raise": [('raise money', '筹款'), ("raise one's hand", '举手'), ('raise a question', '提出问题')],
    "rate": [('at any rate', '无论如何'), ('interest rate', '利率'), ('at the rate of', '以…速度')],
    "reach": [('reach for', '伸手去拿'), ('reach an agreement', '达成协议'), ('out of reach', '够不着')],
    "real": [('for real', '认真的'), ('real life', '现实生活'), ('real name', '真名')],
    "realise": [("realise one's dream", '实现梦想'), ('suddenly realise', '突然意识到'), ('realise the truth', '意识到真相')],
    "really": [('really want', '真的想要'), ('really good', '真的很好'), ('not really', '不真的')],
    "reason": [('for this reason', '因此'), ('good reason', '好理由'), ('the reason why', '…的原因')],
    "receive": [('receive a letter', '收到信'), ('receive help', '得到帮助'), ('receive training', '接受培训')],
    "recent": [('in recent years', '近年来'), ('recent news', '最近消息'), ('recent study', '近期研究')],
    "record": [('break a record', '打破纪录'), ('on record', '记录在案'), ('medical record', '病历')],
    "reduce": [('reduce costs', '降低成本'), ('reduce stress', '减轻压力'), ('reduce pollution', '减少污染')],
    "relationship": [('good relationship', '良好关系'), ('family relationship', '家庭关系'), ('build a relationship', '建立关系')],
    "remain": [('remain calm', '保持冷静'), ('remain silent', '保持沉默'), ('remain the same', '保持不变')],
    "remember": [('remember to do', '记得做'), ('remember doing', '记得做过'), ('as I remember', '据我记得')],
    "report": [('news report', '新闻报道'), ('report to', '向…汇报'), ('annual report', '年度报告')],
    "represent": [('represent the class', '代表班级'), ('represent a company', '代表公司'), ('represent our school', '代表我校')],
    "require": [('require patience', '需要耐心'), ('as required', '按要求'), ('require sb to do', '要求某人做')],
    "research": [('do research', '做研究'), ('research paper', '研究论文'), ('scientific research', '科学研究')],
    "rest": [('the rest of', '其余的'), ('take a rest', '休息'), ('for the rest', '其余时间')],
    "result": [('as a result', '因此'), ('result in', '导致'), ('exam result', '考试成绩')],
    "return": [('return to', '返回'), ('in return', '作为回报'), ('return home', '回家')],
    "right": [('all right', '好的'), ('right away', '立刻'), ('human rights', '人权')],
    "road": [('on the road', '在路上'), ('road trip', '公路旅行'), ('main road', '主干道')],
    "role": [('play a role', '起作用'), ('role model', '榜样'), ('leading role', '主角')],
    "rule": [('as a rule', '通常'), ('break the rules', '违反规则'), ('rule out', '排除')],
    "same": [('the same', '相同的'), ('at the same time', '同时'), ('same as', '和…一样')],
    "say": [('say hello', '打招呼'), ('say sorry', '道歉'), ('that is to say', '也就是说')],
    "season": [('rainy season', '雨季'), ('in season', '当季'), ('football season', '足球赛季')],
    "second": [('second thought', '再想想'), ('second place', '第二名'), ('every second', '每秒')],
    "security": [('national security', '国家安全'), ('security check', '安检'), ('job security', '工作保障')],
    "seek": [('seek help', '寻求帮助'), ('seek for', '寻找'), ('seek advice', '征求意见')],
    "seem": [('seem to be', '似乎是'), ('seem like', '好像'), ('seem happy', '看起来高兴')],
    "sell": [('sell out', '售罄'), ('sell well', '卖得好'), ('hard to sell', '难卖')],
    "send": [('send a message', '发消息'), ('send for', '派人去请'), ('send back', '退回')],
    "sense": [('make sense', '有意义'), ('common sense', '常识'), ('sense of humour', '幽默感')],
    "serve": [('serve as', '充当'), ('serve the people', '为人民服务'), ('serve food', '上菜')],
    "service": [('customer service', '客服'), ('in service', '在职'), ('public service', '公共服务')],
    "set": [('set up', '建立'), ('set off', '出发'), ('set an example', '树立榜样')],
    "several": [('several times', '几次'), ('several days', '好几天'), ('several people', '几个人')],
    "shall": [('shall we go?', '我们走吧？'), ('shall I help?', '我来帮忙好吗？'), ('Shall we dance?', '跳支舞好吗？')],
    "should": [('should study hard', '应该努力学习'), ('should be fine', '应该没问题'), ('should not worry', '不必担心')],
    "side": [('on the side', '在旁边'), ('side by side', '并肩'), ('side effect', '副作用')],
    "since": [('ever since', '自从'), ('since then', '从那以后'), ('long since', '很久以前')],
    "single": [('single room', '单人间'), ('every single', '每一个'), ('single parent', '单亲')],
    "situation": [('current situation', '当前形势'), ('difficult situation', '困境'), ('in this situation', '在这种情况下')],
    "so": [('so far', '到目前为止'), ('so that', '以便'), ('so much', '如此多')],
    "social": [('social media', '社交媒体'), ('social life', '社交生活'), ('social problem', '社会问题')],
    "society": [('modern society', '现代社会'), ('in society', '在社会上'), ('human society', '人类社会')],
    "someone": [('someone else', '别人'), ('someone special', '特别的人'), ('someone called', '有人叫')],
    "something": [('something wrong', '出问题了'), ('something else', '别的什么'), ('something like', '有点像')],
    "sometimes": [('sometimes feel', '有时感到'), ('sometimes hard', '有时很难')],
    "son": [('elder son', '长子'), ('son and daughter', '儿女'), ('young son', '年幼的儿子')],
    "soon": [('as soon as', '一…就'), ('see you soon', '回头见'), ('come back soon', '快点回来')],
    "south": [('in the south', '在南方'), ('south of', '在…以南'), ('South China', '华南')],
    "space": [('outer space', '外太空'), ('free space', '空闲空间'), ('living space', '生活空间')],
    "speak": [('speak English', '说英语'), ('speak up', '大声说'), ('generally speaking', '一般来说')],
    "special": [('special offer', '特价'), ('nothing special', '没什么特别'), ('special thanks', '特别感谢')],
    "spend": [('spend time on', '花时间于'), ('spend money on', '花钱于'), ('spend the night', '过夜')],
    "stand": [('stand up', '站起来'), ('stand for', '代表'), ('stand out', '突出')],
    "star": [('movie star', '电影明星'), ('rising star', '新星'), ('star sign', '星座')],
    "start": [('start with', '从…开始'), ('start doing', '开始做'), ('start from scratch', '从零开始')],
    "state": [('state clearly', '明确说明'), ('in a state', '处于…状态'), ('state school', '公立学校')],
    "stay": [('stay up', '熬夜'), ('stay away', '远离'), ('stay in touch', '保持联系')],
    "step": [('step by step', '逐步'), ('take steps', '采取措施'), ('step forward', '向前迈')],
    "still": [('still alive', '还活着'), ('stand still', '站着不动'), ('still waiting', '还在等')],
    "stop": [('stop doing', '停止做'), ('bus stop', '公交站'), ('stop by', '顺便拜访')],
    "store": [('department store', '百货商店'), ('in store', '储备着'), ('convenience store', '便利店')],
    "story": [('tell a story', '讲故事'), ('short story', '短篇'), ('success story', '成功故事')],
    "street": [('on the street', '在街上'), ('main street', '主街'), ('cross the street', '过马路')],
    "strong": [('strong enough', '足够强'), ('strong wind', '强风'), ('strong coffee', '浓咖啡')],
    "subject": [('on the subject of', '关于'), ('change the subject', '换话题'), ('school subject', '学科')],
    "such": [('such as', '例如'), ('such a', '这样一个'), ('as such', '就其本身')],
    "suggest": [('suggest doing sth', '建议做某事'), ('strongly suggest', '强烈建议'), ('suggest a plan', '提出建议')],
    "summer": [('summer vacation', '暑假'), ('last summer', '去年夏天'), ('hot summer', '炎热的夏天')],
    "support": [('support sb', '支持某人'), ('financial support', '经济支持'), ('in support of', '支持')],
    "sure": [('make sure', '确保'), ('for sure', '肯定'), ('not sure', '不确定')],
    "system": [('education system', '教育体系'), ('operating system', '操作系统'), ('immune system', '免疫系统')],
    "table": [('on the table', '在桌上'), ('table tennis', '乒乓球'), ('dinner table', '餐桌')],
    "take": [('take care', '小心'), ('take part in', '参加'), ('take place', '发生')],
    "tax": [('income tax', '所得税'), ('tax rate', '税率'), ('pay tax', '纳税')],
    "teach": [('teach English', '教英语'), ('teach sb a lesson', '给某人教训'), ('teach by example', '以身作则')],
    "teacher": [('English teacher', '英语老师'), ('head teacher', '班主任'), ('music teacher', '音乐老师')],
    "team": [('team work', '团队合作'), ('team member', '队员'), ('football team', '足球队')],
    "technology": [('modern technology', '现代技术'), ('information technology', '信息技术'), ('science and technology', '科学技术')],
    "tell": [('tell the truth', '说实话'), ('tell a story', '讲故事'), ('tell sb to do', '叫某人做')],
    "term": [('long term', '长期'), ('in terms of', '就…而言'), ('school term', '学期')],
    "test": [('take a test', '参加考试'), ('blood test', '验血'), ('test paper', '试卷')],
    "than": [('more than', '多于'), ('less than', '少于'), ('rather than', '而不是')],
    "thank": [('thank you', '谢谢'), ('thank sb for', '因…感谢某人'), ('thanks a lot', '多谢')],
    "their": [],
    "them": [],
    "themselves": [('by themselves', '独自'), ('enjoy themselves', '玩得开心'), ('help themselves', '自行取用')],
    "then": [('and then', '然后'), ('since then', '从那以后'), ('by then', '到那时')],
    "these": [('these days', '这些天'), ('one of these days', '总有一天')],
    "thing": [('the same thing', '同样的事'), ('first thing', '第一件事'), ('among other things', '除了别的')],
    "think": [('think about', '考虑'), ('think of', '想到'), ('think over', '仔细考虑')],
    "those": [('those days', '那些日子'), ('one of those', '其中之一')],
    "though": [('even though', '即使'), ('as though', '好像')],
    "through": [('go through', '经历'), ('through the door', '穿过门'), ('all through', '整个期间')],
    "throw": [('throw away', '扔掉'), ('throw up', '呕吐'), ('throw a party', '办派对')],
    "top": [('on top of', '在…上面'), ('top student', '尖子生'), ('from top to bottom', '从上到下')],
    "toward": [('move toward', '朝…移动'), ('attitude toward', '对…的态度'), ('step toward', '朝…迈步')],
    "town": [('home town', '家乡'), ('small town', '小镇'), ('across town', '全城')],
    "true": [('come true', '实现'), ('true story', '真实故事'), ('true friend', '真朋友')],
    "try": [('try to do', '尽力做'), ("try one's best", '尽力'), ('have a try', '试一试')],
    "turn": [('turn on', '打开'), ('turn off', '关掉'), ('turn into', '变成')],
    "type": [('type of', '…的类型'), ('blood type', '血型'), ('type in', '输入')],
    "under": [('under control', '在控制下'), ('under pressure', '在压力下'), ('under the table', '在桌子下')],
    "understand": [('understand each other', '互相理解'), ('hard to understand', '难懂'), ('help me understand', '帮我理解')],
    "until": [('wait until', '等到'), ('not until', '直到…才'), ('until now', '直到现在')],
    "upon": [('once upon a time', '从前'), ('depend upon', '取决于'), ('upon arrival', '到达时')],
    "use": [('make use of', '利用'), ('in use', '在使用中'), ('use up', '用完')],
    "value": [('of great value', '很有价值'), ('value for money', '物有所值'), ('core values', '核心价值观')],
    "view": [('in view of', '鉴于'), ('point of view', '观点'), ('with a view to', '为了')],
    "voice": [('in a low voice', '低声'), ("raise one's voice", '提高嗓门'), ('with one voice', '异口同声')],
    "wait": [('wait for', '等待'), ('wait a minute', '等一下'), ("can't wait", '等不及')],
    "wall": [('on the wall', '在墙上'), ('wall clock', '挂钟'), ('Great Wall', '长城')],
    "want": [('want to go', '想去'), ('want sb to help', '想让人帮忙'), ('want more time', '想要更多时间')],
    "war": [('civil war', '内战'), ('at war', '在战争中'), ('world war', '世界大战')],
    "watch": [('watch TV', '看电视'), ('watch out', '小心'), ('keep watch', '守望')],
    "water": [('drink water', '喝水'), ('water supply', '供水'), ('under water', '在水下')],
    "way": [('by the way', '顺便说'), ('on the way', '在路上'), ('in a way', '在某种程度上')],
    "week": [('last week', '上周'), ('next week', '下周'), ('week by week', '逐周')],
    "west": [('in the west', '在西方'), ('west of the city', '城西'), ('the Wild West', '西部荒野')],
    "when": [('when to start', '何时开始'), ('even when tired', '即使累了'), ('when possible', '可能时')],
    "whether": [('whether or not', '是否'), ('whether to', '是否')],
    "which": [('in which', '在其中'), ('which one', '哪一个'), ('which way', '哪条路')],
    "while": [('for a while', '一会儿'), ('a while ago', '刚才'), ('all the while', '一直')],
    "whole": [('the whole day', '整天'), ('on the whole', '总的来说'), ('as a whole', '整体上')],
    "why": [('why not', '为什么不'), ("that's why", '这就是为什么'), ('no reason why', '没理由')],
    "wife": [('husband and wife', '夫妻'), ('my wife', '我妻子'), ('future wife', '未来的妻子')],
    "will": [('will come soon', '很快会来'), ('will be fine', '会好的'), ('will not give up', '不会放弃')],
    "win": [('win a prize', '获奖'), ('win the game', '赢得比赛'), ('win back', '赢回')],
    "within": [('within reach', '够得着'), ('within a week', '一周内'), ('within limits', '在限度内')],
    "without": [('without doubt', '毫无疑问'), ('do without', '没有也行'), ('without a word', '一声不吭')],
    "woman": [('young woman', '年轻女子'), ('old woman', '老妇人'), ('working woman', '职业女性')],
    "word": [('in a word', '总之'), ("keep one's word", '守信用'), ('word for word', '逐字')],
    "work": [('work hard', '努力工作'), ('at work', '在工作'), ('work out', '锻炼/解决')],
    "worker": [('factory worker', '工厂工人'), ('office worker', '上班族'), ('social worker', '社工')],
    "would": [('would like to', '想要'), ('would rather stay', '宁愿留下'), ('would be great', '那就太好了')],
    "wrong": [('go wrong', '出错'), ('wrong answer', '错误答案'), ('something wrong', '出问题了')],
    "year": [('last year', '去年'), ('New Year', '新年'), ('year by year', '逐年')],
    "yet": [('not yet', '还没有'), ('as yet', '迄今')],
    "young": [('young people', '年轻人'), ('young age', '年轻时'), ('stay young', '保持年轻')],}


def _phrase_contains_word(word: str, phrase: str) -> bool:
    """Check target word appears as whole word or common inflection."""
    phrase_l = phrase.lower()
    word_l = word.lower()
    if re.search(rf"\b{re.escape(word_l)}\b", phrase_l):
        return True
    if word_l.endswith("e"):
        stems = [word_l, word_l + "d", word_l + "ing", word_l[:-1] + "ing", word_l + "s"]
    elif word_l.endswith("y") and len(word_l) > 2 and word_l[-2] not in "aeiou":
        stem = word_l[:-1]
        stems = [word_l, stem + "ies", stem + "ied", word_l + "ing", word_l + "s"]
    else:
        stems = [word_l, word_l + "s", word_l + "es", word_l + "ed", word_l + "ing"]
    for stem in stems:
        if re.search(rf"\b{re.escape(stem)}\b", phrase_l):
            return True
    return False


def verify_coverage() -> str:
    """Validate COLLOCATIONS covers all top-500 base words."""
    expected = load_top500_base_words()
    expected_set = set(expected)
    actual_set = set(COLLOCATIONS.keys())
    missing = sorted(expected_set - actual_set)
    extra = sorted(actual_set - expected_set)
    issues: list[str] = []
    if missing:
        issues.append(f"missing words: {', '.join(missing)}")
    if extra:
        issues.append(f"extra words: {', '.join(extra)}")
    for word in expected:
        items = COLLOCATIONS.get(word, [])
        if word not in COLLOCATIONS:
            issues.append(f"{word}: not in COLLOCATIONS")
            continue
        if len(items) > 3:
            issues.append(f"{word}: more than 3 items")
        if word in EMPTY_PRONOUNS and items:
            issues.append(f"{word}: pronoun should be empty")
        for en, zh in items:
            if not en.strip() or not zh.strip():
                issues.append(f"{word}: empty en/zh")
            if not _phrase_contains_word(word, en):
                issues.append(f"{word}: phrase missing word: {en}")
    total_phrases = sum(len(COLLOCATIONS.get(w, [])) for w in expected)
    if issues:
        return f"FAIL: {len(expected)} words, {total_phrases} phrases, {len(issues)} issues\n" + "\n".join(issues)
    return f"OK: {len(expected)} words, {total_phrases} phrases, 0 issues"
