#!/usr/bin/env python3
"""Refine fallback examples via sequential Tatoeba fetch + colloquial scoring."""

from __future__ import annotations

import json
from pathlib import Path

from generate_examples import (
    OUTPUT_PATH,
    base_word,
    fallback_example,
    fetch_tatoeba,
    score_sentence,
)

ASSETS = Path(__file__).resolve().parent / "assets"
TOP500_PATH = ASSETS / "_top500_words.json"

# Colloquial overrides where Tatoeba tends to be formal or misses the word.
EXTRA: dict[str, tuple[str, str]] = {
    "american": ("I'm American.", "我是美国人。"),
    "case": ("In that case.", "那样的话。"),
    "system": ("The system's down.", "系统挂了。"),
    "programme": ("What's on the programme?", "节目单上有什么？"),
    "during": ("Don't talk during the movie.", "看电影别说话。"),
    "government": ("The government raised taxes.", "政府加税了。"),
    "mr.": ("Mr. Smith is here.", "史密斯先生到了。"),
    "area": ("This area is nice.", "这片区不错。"),
    "national": ("It's a national holiday.", "今天是国定假日。"),
    "fact": ("In fact, I agree.", "其实我也同意。"),
    "lot": ("Thanks a lot.", "非常感谢。"),
    "kind": ("What kind?", "哪种？"),
    "since": ("Since when?", "从什么时候起？"),
    "service": ("Service was great.", "服务很好。"),
    "around": ("Look around.", "四处看看。"),
    "until": ("Wait until I get back.", "等我回来。"),
    "line": ("Stand in line.", "排队。"),
    "political": ("Let's not get political.", "别谈政治了。"),
    "among": ("Among friends.", "朋友之间。"),
    "member": ("Family member.", "家庭成员。"),
    "law": ("That's the law.", "法律就是这样。"),
    "least": ("At least try.", "至少试一下。"),
    "president": ("The president spoke today.", "总统今天讲话了。"),
    "several": ("Several times.", "好几次了。"),
    "information": ("For more information.", "欲知详情。"),
    "social": ("Social media.", "社交媒体。"),
    "whether": ("I don't know whether.", "我不知道是否。"),
    "anything": ("Anything else?", "还要别的吗？"),
    "public": ("In public.", "在公共场合。"),
    "level": ("Level up.", "升级。"),
    "door": ("Open the door.", "开门。"),
    "health": ("Health comes first.", "健康第一。"),
    "person": ("Nice person.", "好人。"),
    "art": ("It's an art.", "这是门艺术。"),
    "war": ("No more war.", "不要再打仗了。"),
    "history": ("That's history.", "那是过去的事了。"),
    "party": ("Great party!", "派对太棒了！"),
    "within": ("Within an hour.", "一小时内。"),
    "result": ("As a result.", "结果。"),
    "reason": ("What's the reason?", "什么原因？"),
    "low": ("Battery's low.", "电量低了。"),
    "research": ("Do some research.", "做下调研。"),
    "early": ("Too early.", "太早了。"),
    "moment": ("One moment, please.", "请稍等。"),
    "himself": ("He did it himself.", "他自己做的。"),
    "air": ("Fresh air.", "新鲜空气。"),
    "teacher": ("My teacher's nice.", "我老师很好。"),
    "force": ("Don't force me.", "别逼我。"),
    "enough": ("That's enough.", "够了。"),
    "education": ("Education matters.", "教育很重要。"),
    "across": ("Across the street.", "街对面。"),
    "although": ("Although it's hard.", "虽然很难。"),
    "foot": ("On foot.", "步行。"),
    "second": ("Just a second.", "等一下。"),
    "maybe": ("Maybe later.", "也许待会儿。"),
    "toward": ("Head toward the exit.", "朝出口走。"),
    "able": ("I'll be able to.", "我能行的。"),
    "policy": ("Company policy.", "公司规定。"),
    "everything": ("Everything's fine.", "一切都好。"),
    "process": ("It's a long process.", "过程很长。"),
    "probably": ("Probably not.", "大概不会。"),
    "human": ("Human nature.", "人性。"),
    "market": ("Go to the market.", "去市场。"),
    "sense": ("That makes sense.", "有道理。"),
    "nation": ("The whole nation.", "全国。"),
    "college": ("I'm in college.", "我在上大学。"),
    "interest": ("No interest.", "没兴趣。"),
    "death": ("Life and death.", "生死。"),
    "course": ("Of course!", "当然！"),
    "someone": ("Someone's at the door.", "有人敲门。"),
    "experience": ("Great experience.", "很棒的体验。"),
    "behind": ("Behind you!", "在你后面！"),
    "local": ("Local food.", "当地美食。"),
    "effect": ("Side effect.", "副作用。"),
    "class": ("First class.", "头等舱。"),
    "control": ("Out of control.", "失控了。"),
    "care": ("I don't care.", "我不在乎。"),
    "perhaps": ("Perhaps tomorrow.", "也许明天。"),
    "late": ("Sorry I'm late.", "抱歉来晚了。"),
    "hard": ("Work hard.", "努力工作。"),
    "field": ("In the field.", "在实地。"),
    "else": ("What else?", "还有什么？"),
    "former": ("My former boss.", "我以前的老板。"),
    "major": ("Major problem.", "大问题。"),
    "sometimes": ("Sometimes I wonder.", "有时我会想。"),
    "development": ("Under development.", "开发中。"),
    "themselves": ("They did it themselves.", "他们自己做的。"),
    "role": ("Play a role.", "发挥作用。"),
    "effort": ("Good effort.", "努力不错。"),
    "rate": ("At any rate.", "不管怎样。"),
    "strong": ("Stay strong.", "坚强点。"),
    "possible": ("Anything's possible.", "一切皆有可能。"),
    "heart": ("With all my heart.", "全心全意。"),
    "drug": ("No drugs.", "禁止毒品。"),
    "leader": ("Team leader.", "队长。"),
    "light": ("Turn on the light.", "开灯。"),
    "voice": ("Lower your voice.", "小声点。"),
    "wife": ("My wife and I.", "我和我妻子。"),
    "whole": ("The whole thing.", "整件事。"),
    "police": ("Call the police.", "报警。"),
    "mind": ("Never mind.", "没关系。"),
    "price": ("What's the price?", "多少钱？"),
    "decision": ("Good decision.", "好决定。"),
    "son": ("My son's five.", "我儿子五岁了。"),
    "view": ("Nice view.", "风景不错。"),
    "relationship": ("It's complicated.", "很复杂。"),
    "town": ("Small town.", "小镇。"),
    "road": ("Down the road.", "沿着路。"),
    "drive": ("Can you drive?", "你会开车吗？"),
    "arm": ("Arm in arm.", "手挽手。"),
    "true": ("That's true.", "没错。"),
    "federal": ("Federal law.", "联邦法律。"),
    "difference": ("What's the difference?", "有什么区别？"),
    "thank": ("Thank you so much.", "太谢谢了。"),
    "value": ("Good value.", "很划算。"),
    "international": ("International flight.", "国际航班。"),
    "building": ("Nice building.", "楼不错。"),
    "action": ("Action!", "行动！"),
    "full": ("I'm full.", "我饱了。"),
    "model": ("Role model.", "榜样。"),
    "season": ("Season's over.", "赛季结束了。"),
    "society": ("Modern society.", "现代社会。"),
    "tax": ("Tax included.", "含税。"),
    "director": ("Film director.", "电影导演。"),
    "position": ("Good position.", "位置不错。"),
    "especially": ("Especially you.", "尤其是你。"),
    "record": ("Break a record.", "破纪录。"),
    "paper": ("Paper or plastic?", "纸袋还是塑料袋？"),
    "special": ("Today's special.", "今日特价。"),
    "space": ("Need more space.", "需要更多空间。"),
    "ground": ("On the ground.", "在地上。"),
    "form": ("Fill out this form.", "填这张表。"),
    "event": ("Big event.", "大活动。"),
    "official": ("Official notice.", "正式通知。"),
    "matter": ("What's the matter?", "怎么了？"),
    "everyone": ("Hi, everyone.", "大家好。"),
    "centre": ("City centre.", "市中心。"),
    "couple": ("A couple of days.", "几天。"),
    "project": ("Group project.", "小组项目。"),
    "base": ("Base on facts.", "基于事实。"),
    "activity": ("Fun activity.", "有趣的活动。"),
    "star": ("You're a star.", "你真棒。"),
    "table": ("Set the table.", "摆桌子。"),
    "court": ("See you in court.", "法庭见。"),
    "teach": ("Teach me.", "教教我。"),
    "oil": ("Olive oil.", "橄榄油。"),
    "half": ("Half price.", "半价。"),
    "situation": ("Tough situation.", "处境艰难。"),
    "cost": ("How much does it cost?", "多少钱？"),
    "industry": ("Film industry.", "电影业。"),
    "figure": ("I figure so.", "我想是的。"),
    "street": ("Main street.", "主街。"),
    "itself": ("The door opened itself.", "门自己开了。"),
    "either": ("Either way.", "不管怎样。"),
    "data": ("No data.", "没数据。"),
    "quite": ("Quite good.", "挺好的。"),
    "clear": ("All clear.", "一切清楚。"),
    "practice": ("Practice makes perfect.", "熟能生巧。"),
    "practise": ("Practise every day.", "每天练习。"),
    "piece": ("A piece of cake.", "小菜一碟。"),
    "land": ("Safe landing.", "安全着陆。"),
    "recent": ("Recent news.", "最近的消息。"),
    "describe": ("Hard to describe.", "很难描述。"),
    "product": ("New product.", "新产品。"),
    "doctor": ("See a doctor.", "看医生。"),
    "wall": ("Hit the wall.", "撞墙了。"),
    "patient": ("Be patient.", "耐心点。"),
    "worker": ("Hard worker.", "工作努力。"),
    "news": ("Good news!", "好消息！"),
    "test": ("Pop quiz test.", "随堂测验。"),
    "movie": ("Good movie.", "好电影。"),
    "certain": ("For certain.", "确定。"),
    "north": ("Head north.", "往北走。"),
    "personal": ("Personal matter.", "私事。"),
    "technology": ("New technology.", "新技术。"),
    "step": ("Step by step.", "一步一步。"),
    "computer": ("My computer crashed.", "我电脑崩了。"),
    "type": ("What type?", "哪种类型？"),
    "attention": ("Pay attention.", "注意。"),
    "nearly": ("Nearly done.", "快完成了。"),
    "organization": ("Non-profit organization.", "非营利组织。"),
    "century": ("21st century.", "二十一世纪。"),
    "evidence": ("No evidence.", "没证据。"),
    "difficult": ("Too difficult.", "太难了。"),
    "soon": ("See you soon.", "回头见。"),
    "culture": ("Pop culture.", "流行文化。"),
    "billion": ("Billions of stars.", "无数星星。"),
    "chance": ("Last chance.", "最后机会。"),
    "energy": ("Full of energy.", "精力充沛。"),
    "period": ("That's final, period.", "就这样，句号。"),
    "summer": ("This summer.", "今年夏天。"),
    "realise": ("I didn't realise.", "我没意识到。"),
    "available": ("Not available.", "没空。"),
    "likely": ("Most likely.", "很可能。"),
    "term": ("Long term.", "长期。"),
    "letter": ("Write a letter.", "写封信。"),
    "condition": ("In good condition.", "状况良好。"),
    "choice": ("Your choice.", "你选。"),
    "single": ("I'm single.", "我单身。"),
    "rule": ("Rules are rules.", "规矩就是规矩。"),
    "daughter": ("My daughter's cute.", "我女儿很可爱。"),
    "administration": ("School administration.", "学校行政。"),
    "south": ("Go south.", "往南走。"),
    "husband": ("My husband's cooking.", "我丈夫在做饭。"),
    "floor": ("Third floor.", "三楼。"),
    "campaign": ("Ad campaign.", "广告活动。"),
    "material": ("Raw material.", "原材料。"),
    "population": ("Growing population.", "人口增长。"),
    "medical": ("Medical help.", "医疗帮助。"),
    "hospital": ("Go to the hospital.", "去医院。"),
    "church": ("Go to church.", "去教堂。"),
    "defence": ("In my defence.", "替我说句话。"),
    "anyone": ("Anyone home?", "有人吗？"),
    "increase": ("Price increase.", "涨价了。"),
    "security": ("Security check.", "安检。"),
    "bank": ("Which bank?", "哪家银行？"),
    "myself": ("I did it myself.", "我自己做的。"),
    "west": ("Go west.", "往西走。"),
    "board": ("On board.", "在船上。"),
    "seek": ("Seek help.", "寻求帮助。"),
    "per": ("Per person.", "每人。"),
    "subject": ("Change the subject.", "换个话题。"),
    "officer": ("Police officer.", "警察。"),
    "private": ("Keep it private.", "保密。"),
    "rest": ("Get some rest.", "休息一下。"),
    "performance": ("Great performance.", "表演很棒。"),
    "fight": ("Don't fight.", "别打架。"),
    "throw": ("Throw it away.", "扔掉。"),
    "top": ("On top.", "在上面。"),
    "goal": ("Score a goal.", "进球！"),
    "order": ("Order food.", "点餐。"),
    "author": ("Who's the author?", "作者是谁？"),
    "fill": ("Fill it up.", "加满。"),
    "represent": ("I represent the team.", "我代表队伍。"),
    "focus": ("Stay focused.", "保持专注。"),
    "foreign": ("Foreign language.", "外语。"),
    "blood": ("Blood type.", "血型。"),
    "upon": ("Once upon a time.", "从前。"),
    "agency": ("Travel agency.", "旅行社。"),
    "nature": ("Force of nature.", "自然的力量。"),
    "store": ("Grocery store.", "杂货店。"),
    "note": ("Take notes.", "做笔记。"),
    "fine": ("I'm fine.", "我很好。"),
    "near": ("Near the station.", "车站附近。"),
    "movement": ("Slow movement.", "动作慢点。"),
    "page": ("Turn the page.", "翻页。"),
    "against": ("Against the wall.", "靠墙。"),
    "part": ("Part of the team.", "团队一员。"),
    "place": ("Place your order.", "请下单。"),
    "house": ("House party.", "家庭派对。"),
    "water": ("Still or sparkling water?", "静水还是气泡水？"),
    "book": ("Book a room.", "订房间。"),
    "programme": ("TV programme.", "电视节目。"),
    "mr": ("Excuse me, Mr.", "不好意思，先生。"),
}


def main() -> None:
    data = json.loads(OUTPUT_PATH.read_text(encoding="utf-8"))
    words = json.loads(TOP500_PATH.read_text(encoding="utf-8"))
    by_base = {base_word(w["word"]): w for w in words}

    updated = 0
    for key, entry in data["examples"].items():
        if entry.get("source") != "fallback":
            continue
        if key in EXTRA:
            en, zh = EXTRA[key]
            entry.update(en=en, zh=zh, source="manual")
            updated += 1
            continue
        try:
            candidates = fetch_tatoeba(key)
            if candidates:
                entry.update(en=candidates[0][0], zh=candidates[0][1], source="tatoeba")
                updated += 1
                continue
        except Exception:
            pass
        item = by_base.get(key, {})
        en, zh = fallback_example(key, item.get("definition", ""), item.get("coca_meanings", []))
        entry.update(en=en, zh=zh)

    stats = {"manual": 0, "tatoeba": 0, "fallback": 0}
    for entry in data["examples"].values():
        stats[entry.get("source", "fallback")] += 1
    data["meta"]["stats"] = stats

    OUTPUT_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Updated {updated} entries")
    print(f"Stats: {stats}")


if __name__ == "__main__":
    main()
